# Generated by Django 5.1.1 on 2024-10-08 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_qrcode_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='qrcode',
            name='data',
            field=models.TextField(default='Default QR Code Data'),
        ),
    ]
